acme_essentials_book:
    resource: "@AcmeEssentialsBookBundle/Resources/config/routing.yml"
    prefix:   /

#acme_essentials_book_blog:
#    resource: "@AcmeEssentialsBookBundle/Controller/BlogController.php"
#    type:   annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# AcmeDemoBundle routes (to be removed)
_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"