acme_essentials_book_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeEssentialsBookBundle:Default:index }

acme_esb_rand:
  path: /random/{limit}
  defaults: { _controller: AcmeEssentialsBookBundle:Random:index }