services:
    acme_essentials_book.form.task:
        class: Acme\EssentialsBookBundle\Form\Type\TaskType
        tags:
            - {name: form.type, alias:taskFrm}
#        arguments: [@service_id, "plain_value", %parameter%]

    my_mailer:
        class: Acme\EssentialsBookBundle\Helpers\BookMailer
        arguments: [sendmail fake]
